name: 'Destroy'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: 'Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role
        aws-region: us-east-1
        role-session-name: GitHubActionsSyntheticCanaryDestroy

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: latest
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
